version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run: sudo apt-get install python3-distutils
      - run: sudo apt-get install python3-apt
      - run: touch local.properties
      - run: ./gradlew androidDependencies
      - run:
          command: ./gradlew build
