version: 2.1

orbs:
  android: circleci/android@0.2.1
  python: circleci/python@1.0.0

jobs:
  build:
      
    executor: android/android

    steps:
      - checkout
      - python/dist
      - run: touch local.properties
      - run: ./gradlew androidDependencies
      - run:
          command: ./gradlew build
